version: '3'

volumes:
  jobbo_local_postgres_data: {}
  jobbo_local_postgres_data_backups: {}

services:
  app: &app
    user: "1000"
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: jobbo_local_django
    container_name: jobbo_local_django
    depends_on:
      - db
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"

  db:
    image: postgres:14.1-bullseye
    container_name: jobbo_local_postgres
    volumes:
      - jobbo_local_postgres_data:/var/lib/postgresql/data:Z
      - jobbo_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: jobbo_local_redis

  celeryworker:
    <<: *app
    image: jobbo_local_celeryworker
    container_name: jobbo_local_celeryworker
    depends_on:
      - redis
      - db
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *app
    image: jobbo_local_celerybeat
    container_name: jobbo_local_celerybeat
    depends_on:
      - redis
      - db
    ports: []
    command: /start-celerybeat

  flower:
    <<: *app
    image: jobbo_local_flower
    container_name: jobbo_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
