# Generated by Django 4.2.2 on 2024-10-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabbo', '0010_add_hype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='board',
            field=models.IntegerField(choices=[(1, 'No Fluff'), (2, 'Just Join It')], default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='JobBoard',
        ),
    ]
