# Generated by Django 4.2.2 on 2024-10-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grabbo', '0011_alter_job_board_delete_jobboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblocation',
            name='is_covid_remote',
        ),
    ]
